name: Test React Application 2

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
  push:
    branches: [ main, dev2 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install dependencies
        run: npx playwright install

      - name: Install dependencies
        run: sudo apt install -y \
            libwoff1 \
            libvpx7 \
            libevent-2.1-7 \
            libopus0 \
            libgstreamer-plugins-base1.0-0 \
            libgstreamer1.0-0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            libharfbuzz-icu0 \
            libhyphen0 \
            libmanette-0.2-0 \
            flite \
            libgles2 \
            libx264-160

      - name: Run tests 2
        run: npm run e2e-tests